Update data connect template to use Open-VSX Firebase extension
project-idx/community-templates pull request #19
Opened 2024-09-28 23:50 UTC by hlshen

2024-09-30 16:27 UTC, yuchenshi approved these changes

2024-09-30 16:29 UTC, maneesht approved these changes

2024-09-30 17:05 UTC, fredzqm approved these changes

2024-10-03 23:30 UTC, maneesht requested changes

2024-10-03 23:30 UTC, maneesht commented on dataconnect/dev.nix
> -  };
Removing the let causes a syntax error. I'll include the fix in my branch.

2024-10-07 18:21 UTC, joehan approved these changes

2024-10-22 20:50 UTC, rodydavis commented
LGTM

2025-03-04 21:59 UTC, closed without merging