FastAPI template
project-idx/community-templates pull request #2
Opened 2024-07-30 15:52 UTC by srivats22

This PR is to add a FastAPI template to Project IDX.

This was inspired by a request posted in the IDX community site: https://community.idx.dev/t/request-fastapi-python-on-idx/1180

One known issue is after the template it loaded and the onStart script is executed the terminal starts to auto-close cause of an existing bug for python virtual env.

Please let me know if I need to make any modifications or everything is good to merge

Thanks
Srivats

2024-08-03 16:25 UTC, davideast requested changes
Hey Srivats!

Thank you so much for this contribution. It looks mostly good to go with just a few changes needed to make the app open in the preview server at launch. Hopefully the suggestions handle everything but we might have to fix the preview section if I messed up something with the formatting.

2024-08-03 16:25 UTC, davideast commented on fastapi/dev.nix
> +  channel = "stable-23.11"; # or "unstable"
```suggestion
  channel = "stable-24.05"; # or "unstable"
```

2024-08-03 16:25 UTC, davideast commented on fastapi/dev.nix
> +      onStart = { run-server = "./devserver.sh"; };
Instead of `onStart` let's use the preview server instead.

```suggestion
      previews = {
      enable = true;
      previews = {
        web = {
          command = [ "./devserver.sh" ];
          env = { PORT = "$PORT"; };
          manager = "web";
        };
      };
    };
  };
```

2024-08-03 16:25 UTC, davideast commented on fastapi/dev.nix
> +      onStart = { run-server = "./devserver.sh"; };
We'll need to double check the formatting on this one. Multiline suggestions can be tricky.

2024-08-03 16:37 UTC, srivats22 commented
Hey David,

Have addressed the changes as request should be good to go

Thanks

2024-08-05 15:29 UTC, merged

2024-08-05 15:29 UTC, davideast commented
Merged! Thank you so much @srivats22!